id: A0C47F1F5
base_file: fB24B.txt
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:09:19.335019
  last_modified_at: 2022-06-15 20:09:19.335023
