id: A0C47F1F5
base_file: f442B.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:09:19.332990
  last_modified_at: 2022-06-15 20:09:19.332997
