id: A0C47F1F5
base_file: fFB1F.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-15 20:09:19.336878
  last_modified_at: 2022-06-15 20:09:19.336882
